apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tpm-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: tpm-device-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: tpm-device-plugin
    spec:
      priorityClassName: "system-node-critical"
      containers:
      - image: ghcr.io/githedgehog/tpm-device-plugin:latest
        imagePullPolicy: Always
        name: tpm-device-plugin
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: device-plugins
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: device-plugins
        hostPath:
          path: /var/lib/kubelet/device-plugins
